/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


#include <stdint.h>

#define SET_BIT(VAR,BIT)        VAR |=  (1 << (BIT))
#define CLR_BIT(VAR,BIT)          VAR &= ~(1 << (BIT))


#define GPIO_IOPAEN 2
#define RCC_APB2ENR    *((volatile uint32_t*)0x40021018)


#define PORTA_CRH  *((volatile uint32_t*)0X40010804)
#define PORTA_ODR  *((volatile uint32_t*)0X4001080C)
int main(void)
{

	/* Enable clock for GPIO PORTA */
	SET_BIT(RCC_APB2ENR ,GPIO_IOPAEN);

	/* SET mode to output 2MHZ push pull 0010 */
	SET_BIT(PORTA_CRH,21);
	/* Loop forever */
	for(;;)
	{
	SET_BIT(PORTA_ODR,13);
	for(int i =0; i<5000;i++);
	CLR_BIT(PORTA_ODR,13);
	for(int i =0; i<5000;i++);
	}


}
